services:
  simulation:
    image: wngfra/ros2cuda:coppeliasim
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}:/workspace/src/tac3d
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["bash", "src/tac3d/scripts/startup.sh"]
