services:
  jupyterlab:
    image: wngfra/neuralab:base
    container_name: neuralab
    user: root
    working_dir: /notebooks
    volumes:
      - ${PWD}/notebooks:/notebooks
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  loihilab:
    build: docker
    privileged: true
    volumes:
      - ${PWD}:/loihi/notebooks
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    command:
      [
        "jupyter",
        "lab",
        "--allow-root",
        "--no-browser",
        "--notebook-dir=/loihi/notebooks"
      ]

  ros2_mujoco:
    image: wngfra/ros2cuda:base
    container_name: ros2_mujoco
    working_dir: /workspace
    volumes:
      - ${PWD}/tac3d:/workspace/tac3d
      - ${PWD}/models:/workspace/models
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
    network_mode: host
    shm_size: '4gb'
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    command: ["python3", "tac3d/main.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
