name: tac3d

x-shared-data:
  &default-data
  type: bind
  source: ${PWD}/tac3d
  target: /workspace/src/tac3d

volumes:
  shared-volume:


services:
  sensorimotor_simulation:
    image: wngfra/ros2:cuda
    container_name: sensorimotor_simulation_container
    working_dir: /workspace
    volumes:
      - *default-data
      - shared-volume:/workspace
      - ${PWD}/scripts/run.sh:/workspace/run.sh
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    command: [ "bash", "run.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    healthcheck:
      test: ls install || exit 1
      interval: 10s
      timeout: 3s
      retries: 1

  dev:
    image: wngfra/ros2:cuda
    container_name: dev_container
    working_dir: /workspace
    volumes:
      - *default-data
      - shared-volume:/workspace
      - ${PWD}/scripts/dev.sh:/workspace/dev.sh
    command: [ "bash", "dev.sh" ]
    depends_on:
      - sensorimotor_simulation
    stdin_open: true
    tty: true