name: tac3d
services:
  neuralab:
    image: wngfra/neuralab:base
    container_name: neural_jupyterlab
    user: root
    working_dir: /notebooks
    volumes:
      - ${PWD}/notebooks:/notebooks
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    command:
      [
        "jupyter",
        "lab",
        "--allow-root",
        "--no-browser",
        "--notebook-dir=/notebooks"
      ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  ros2_mujoco:
    image: wngfra/ros2cuda:base
    container_name: mujoco_ros2
    working_dir: /workspace
    volumes:
      - ${PWD}/tac3d:/workspace/src/tac3d
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    network_mode: host
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    command: [ "source", "/opt/ros2/humble/setup.bash", "&&", "colcon", "build", "--symlink-install" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
