services:
  app:
    image: ros2cuda:coppeliasim
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    command: bash 
    stdin_open: true
    tty: true
