services:
  simulation:
    image: wngfra/ros2cuda:coppeliasim
    environment:
      - DISPLAY=${DISPLAY}
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - FASTRTPS_DEFAULT_PROFILES_FILE=/shared/scripts/fastrtps-profile.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}/control_interfaces:/workspace/src/control_interfaces
      - ${PWD}/mesh:/shared/mesh
      - ${PWD}/scenes:/shared/scenes
      - ${PWD}/scripts:/shared/scripts
    #network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["bash", "/shared/scripts/start_sim.sh"]
    devices: 
      - "/dev/dri:/dev/dri"
  ml:
    image: wngfra/ros2cuda:ml
    environment:
      - DISPLAY=${DISPLAY}
      - FASTRTPS_DEFAULT_PROFILES_FILE=/shared/scripts/fastrtps-profile.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}/control_interfaces:/workspace/src/control_interfaces
      - ${PWD}/explore_control:/workspace/src/explore_control
      - ${PWD}/scripts:/shared/scripts
      - ${PWD}/sensor_interfaces:/workspace/src/sensor_interfaces
    #network_mode: host
    depends_on: 
      - simulation
    command: ["bash"]
    stdin_open: true
    tty: true
    devices: 
      - "/dev/dri:/dev/dri"
