version: "3"
services:
  simulation:
    image: wngfra/ros2cuda:coppeliasim
    environment:
      - DISPLAY=${DISPLAY}
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}/mesh:/shared/mesh
      - ${PWD}/scenes:/shared/scenes
      - ${PWD}/scripts:/shared/scripts
      - ${PWD}/control_interfaces:/workspace/src/control_interfaces
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["bash", "/shared/scripts/startup.sh"]
    devices: 
      - "/dev/dri:/dev/dri"
  ml:
    image: wngfra/ros2cuda:ml
    environment:
      - DISPLAY=${DISPLAY}
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}/control_interfaces:/workspace/src/control_interfaces
      - ${PWD}/exp_ctrl:/workspace/src/exp_ctrl
      - ${PWD}/sensor_interfaces:/workspace/src/sensor_interfaces
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["bash"]
    stdin_open: true
    tty: true
    devices: 
      - "/dev/dri:/dev/dri"
